# Generated by Django 4.2 on 2025-07-07 05:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(blank=True, max_length=13, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='図書の表紙画像', null=True, upload_to='book_covers')),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, help_text='図書の概要', null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='平均評価', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0, help_text='レビュー数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, help_text='電話番号（ハイフンなし）', max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='郵便番号', max_length=8, null=True)),
                ('address', models.TextField(blank=True, help_text='住所', null=True)),
                ('membership_type', models.CharField(choices=[('regular', '一般会員'), ('student', '学生会員'), ('staff', 'スタッフ'), ('premium', 'プレミアム会員')], default='regular', max_length=20)),
                ('membership_start_date', models.DateField(auto_now_add=True)),
                ('membership_expity_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='プロフィール画像', null=True, upload_to='member_profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField(auto_now_add=True)),
                ('return_due_date', models.DateField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('borrowed', '貸出中'), ('returned', '返却済み'), ('overdue', '延滞')], default='borrowed', max_length=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.member')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5の評価', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='レビュータイトル', max_length=100)),
                ('content', models.TextField(help_text='レビュー内容')),
                ('is_approved', models.BooleanField(default=True, help_text='承認済み')),
                ('is_featured', models.BooleanField(default=True, help_text='おすすめレビュー')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.book')),
                ('likes', models.ManyToManyField(blank=True, help_text='このレビューにいいねした会員', related_name='liked_reviews', to='book_management.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('book', 'member')},
            },
        ),
    ]
