# Generated by Django 4.2 on 2025-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBNコード（重複不可、空白不可）', max_length=13, null=True, unique=True),
        ),
    ]
