# Generated by Django 4.2 on 2025-07-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
    ]
