# Generated by Django 4.2 on 2025-08-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_rename_autor_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_level',
            field=models.CharField(choices=[('regular', '一般会員'), ('student', '学生会員'), ('staff', 'スタッフ'), ('premium', 'プレミアム会員')], default='regular', max_length=10, verbose_name='会員ランク'),
        ),
    ]
